#!/usr/bin/perl -w

use strict;
use warnings;

while (<>) {
    if (/^CREATE OR REPLACE \w+ (\w+)/) {
        if ($1 eq 'os_name' || $1 eq 'pg_typeof') {
            # Never keep this one.
            $print = 0;
        } elsif ($invert ? !$keep{$1} : $keep{$1}) {
            $print = 1;
            print;
        } else {
            $print = 0;
        }
    } else {
        print if $print;
    }
}
